# Generated by Django 5.0.6 on 2024-05-11 21:20

from django.db import migrations


def populate_status(apps, schemaeditro):
    entries = {
        "alpha":"the A team",
        "bravo": "the B team",
        "charlie": "the C team"
    
    }
    Team = apps.get_model("accounts", "Team")
    for key, vaule in entries.items():
        Team_obj = Team(name=key, description=vaule)
        Team_obj.save()
        
        

def populate_status(apps, schemaeditro):
    entries = {
        "developer": "The person on the team who works on the issues",
        "product owner": "The person on the team who writes issues",
        "scrum master": "The teams coach",
    }
    Role = apps.get_model("accounts", "Role")
    for key, vaule in entries.items():
        Role_obj = Role(name=key, description=vaule)
        Role_obj.save()




class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
    ]
